/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
//import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;

import java.awt.*;
public final class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    
    public void MostrarGrafo(){
        System.setProperty("org.graphstream.ui", "swing");
    // Crear un grafo simple
        Graph graph = new SingleGraph("Grafo de prueba");
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addEdge("AB", "A", "B");
        graph.addEdge("BC", "B", "C");
        graph.addEdge("CA", "C", "A");

        // Crear el SwingViewer para integrar con JPanel
        SwingViewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);  // No abrir en una nueva ventana

        // Establecer un tamaño para el ViewPanel y agregarlo al JPanel principal
        viewPanel.setPreferredSize(new Dimension(400, 400));
        this.setLayout(new BorderLayout());
        this.add(viewPanel, BorderLayout.CENTER);
        this.revalidate(); // Para refrescar el panel y mostrar el grafo
        
    }
    public Principal() {
        initComponents();
        MostrarGrafo();
        
    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        sucursales = new javax.swing.JLabel();
        selectsucursales = new javax.swing.JComboBox<>();
        seleccionar = new javax.swing.JButton();
        deseleccionar = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        sucursales.setForeground(new java.awt.Color(0, 0, 0));
        sucursales.setText("SELECCIONE SUCURSALES");

        selectsucursales.setBackground(new java.awt.Color(255, 255, 255));
        selectsucursales.setForeground(new java.awt.Color(0, 0, 0));
        selectsucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        seleccionar.setBackground(new java.awt.Color(255, 255, 255));
        seleccionar.setForeground(new java.awt.Color(0, 0, 0));
        seleccionar.setText("SELECCIONAR");
        seleccionar.setBorder(null);
        seleccionar.setBorderPainted(false);
        seleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });

        deseleccionar.setBackground(new java.awt.Color(255, 255, 255));
        deseleccionar.setForeground(new java.awt.Color(0, 0, 0));
        deseleccionar.setText("DESELECCIONAR");
        deseleccionar.setBorder(null);
        deseleccionar.setBorderPainted(false);
        deseleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deseleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(sucursales)
                .addGap(18, 18, 18)
                .addComponent(selectsucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectsucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sucursales)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarActionPerformed

    private void deseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deseleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deseleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deseleccionar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton seleccionar;
    private javax.swing.JComboBox<String> selectsucursales;
    private javax.swing.JLabel sucursales;
    // End of variables declaration//GEN-END:variables
}
