/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

/**
 *
 * @author rtkn0_z8ls
 */
public class Nuevalinea extends javax.swing.JPanel {

    /**
     * Creates new form Nuevalinea
     */
    public Nuevalinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separador2 = new javax.swing.JSeparator();
        image = new javax.swing.JLabel();
        conexioparadaslabel = new javax.swing.JLabel();
        paradas1 = new javax.swing.JComboBox<>();
        paradas2 = new javax.swing.JComboBox<>();
        conectarparadas = new javax.swing.JButton();
        separador1 = new javax.swing.JLabel();
        conectorlabel = new javax.swing.JLabel();
        agregarparadaslabel = new javax.swing.JLabel();
        separadorazul = new javax.swing.JLabel();
        agregarparada = new javax.swing.JButton();
        inputnewparada = new javax.swing.JTextField();
        mostrargrafo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1032, 438));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separador2.setBackground(new java.awt.Color(153, 153, 153));
        separador2.setForeground(new java.awt.Color(153, 153, 153));
        separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 50, 390));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map (1).png"))); // NOI18N
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        conexioparadaslabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conexioparadaslabel.setForeground(new java.awt.Color(0, 0, 0));
        conexioparadaslabel.setText("Conexion de paradas");
        add(conexioparadaslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 130, -1));

        paradas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(paradas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 180, -1));

        paradas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(paradas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 180, -1));

        conectarparadas.setBackground(new java.awt.Color(153, 255, 204));
        conectarparadas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conectarparadas.setForeground(new java.awt.Color(0, 0, 0));
        conectarparadas.setText("Conectar");
        conectarparadas.setBorder(null);
        conectarparadas.setBorderPainted(false);
        conectarparadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(conectarparadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 120, 40));

        separador1.setText("______________________________________________");
        add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 320, -1));

        conectorlabel.setForeground(new java.awt.Color(0, 0, 0));
        conectorlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conectorlabel.setText("con");
        add(conectorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 50, 40));

        agregarparadaslabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregarparadaslabel.setForeground(new java.awt.Color(0, 0, 0));
        agregarparadaslabel.setText("Agregar paradas");
        add(agregarparadaslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, 30));

        separadorazul.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        separadorazul.setForeground(new java.awt.Color(102, 255, 204));
        separadorazul.setText("_____________________________");
        add(separadorazul, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 259, 270, 20));

        agregarparada.setBackground(new java.awt.Color(153, 255, 204));
        agregarparada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregarparada.setForeground(new java.awt.Color(0, 0, 0));
        agregarparada.setText("Agregar Parada");
        agregarparada.setBorder(null);
        agregarparada.setBorderPainted(false);
        agregarparada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(agregarparada, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 160, 30));

        inputnewparada.setBackground(new java.awt.Color(255, 255, 255));
        inputnewparada.setForeground(new java.awt.Color(153, 153, 153));
        inputnewparada.setText("Nombre de la parada");
        inputnewparada.setBorder(null);
        add(inputnewparada, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 260, 20));

        mostrargrafo.setBackground(new java.awt.Color(153, 255, 204));
        mostrargrafo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrargrafo.setForeground(new java.awt.Color(0, 0, 0));
        mostrargrafo.setText("MOSTRAR GRAFOS");
        mostrargrafo.setBorder(null);
        mostrargrafo.setBorderPainted(false);
        mostrargrafo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(mostrargrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 320, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarparada;
    private javax.swing.JLabel agregarparadaslabel;
    private javax.swing.JButton conectarparadas;
    private javax.swing.JLabel conectorlabel;
    private javax.swing.JLabel conexioparadaslabel;
    private javax.swing.JLabel image;
    private javax.swing.JTextField inputnewparada;
    private javax.swing.JButton mostrargrafo;
    private javax.swing.JComboBox<String> paradas1;
    private javax.swing.JComboBox<String> paradas2;
    private javax.swing.JLabel separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel separadorazul;
    // End of variables declaration//GEN-END:variables
}
