/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
//import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;

import java.awt.*;
import javax.swing.JPanel;
public final class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    
   public void MostrarGrafo(){
        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("Tutorial");

        // Añadir nodos y aristas
        graph.addNode("A");
        graph.addNode("B");
        graph.addNode("C");
        graph.addEdge("AB", "A", "B");
        graph.addEdge("BC", "B", "C");
        graph.addEdge("CA", "C", "A");

        // Usar graph.display() para crear el Viewer
        Viewer viewer = graph.display(false); // 'false' para que no abra una ventana emergente

        // Obtener el componente visual del Viewer
        ViewPanel viewPanel = (ViewPanel) viewer.getDefaultView();

        // Configurar el diseño del JPanel y añadir el ViewPanel
        this.setLayout(new BorderLayout());
        this.add(viewPanel, BorderLayout.CENTER);
        
    }
    public Principal() {
        //initComponents();
        MostrarGrafo();
        
    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    // End of variables declaration//GEN-END:variables
}
